// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYppKIx5R1_MtbkqSEZ6RoEYY9YFdjrfo',
    appId: '1:681151262579:web:d919a26b5c666712341f06',
    messagingSenderId: '681151262579',
    projectId: 'lab-4-f948a',
    authDomain: 'lab-4-f948a.firebaseapp.com',
    storageBucket: 'lab-4-f948a.firebasestorage.app',
    measurementId: 'G-9WR6QSPP5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaxv7hsqtUICZOe5Z51xxb4MtAB6pOqg',
    appId: '1:681151262579:android:18e0b586712bc1bd341f06',
    messagingSenderId: '681151262579',
    projectId: 'lab-4-f948a',
    storageBucket: 'lab-4-f948a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT7xkO8zDNGLgrOq-4SX6o_CK7xMWrZtQ',
    appId: '1:681151262579:ios:367faba6b405b58e341f06',
    messagingSenderId: '681151262579',
    projectId: 'lab-4-f948a',
    storageBucket: 'lab-4-f948a.firebasestorage.app',
    iosClientId: '681151262579-lo84bdgh57bnli2ahue0jknfufgghoej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT7xkO8zDNGLgrOq-4SX6o_CK7xMWrZtQ',
    appId: '1:681151262579:ios:367faba6b405b58e341f06',
    messagingSenderId: '681151262579',
    projectId: 'lab-4-f948a',
    storageBucket: 'lab-4-f948a.firebasestorage.app',
    iosClientId: '681151262579-lo84bdgh57bnli2ahue0jknfufgghoej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYppKIx5R1_MtbkqSEZ6RoEYY9YFdjrfo',
    appId: '1:681151262579:web:c672b32951376320341f06',
    messagingSenderId: '681151262579',
    projectId: 'lab-4-f948a',
    authDomain: 'lab-4-f948a.firebaseapp.com',
    storageBucket: 'lab-4-f948a.firebasestorage.app',
    measurementId: 'G-4T026671JP',
  );
}
